version: '3.5.2.0'


services:
  postgres:
    image: 'postgres:14.5'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=pt6274689'
      - 'POSTGRES_DB=workshop'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080